image: gitpod/workspace-full-vnc

tasks:

- name: SETUP - Download PretextView
  init: |
    cd /workspace
    wget  https://github.com/wtsi-hpag/PretextView/releases/download/0.2.5/PretextView_Linux-x86-64.zip
    unzip PretextView_Linux-x86-64.zip

- name: SETUP - Download MiniProt
  init: |
    cd /workspace
    git clone --depth=1 https://github.com/lh3/miniprot
    cd miniprot
    make

- name: SETUP - Download MicroFinder
  init: |
    cd /workspace
    git clone --depth=1 https://github.com/sanger-tol/MicroFinder.git
    cd MicroFinder
    bundler install

- name: SETUP - PRETEXT-TO-AGP
  init: |
    cd /workspace
    git clone --depth 1 --branch v1.1.3 https://github.com/sanger-tol/agp-tpf-utils.git

- name: SETUP - MAMBA ENVIRONMENT
  init: |
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n rapid -c seqtk pretextgraph -y &&
    gp sync-done bundle

- name: MAIN - TERMINAL TO USE
  # Installing click and ruff in the mamba environment didn't work for some reason
  # It is much easier to install via that mamba env's pip3
  # and then install pretext-to-tpf
  init: gp sync-await bundle # Wait for previous 'inits' to complete
  command: |
    cd /workspace
    /workspace/mambaforge/bin/mamba init bash
    echo 'alias ptt="/workspace/mambaforge/bin/python3 /workspace/agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py"' >> ${HOME}/.bashrc
    source ${HOME}/.bashrc
    mamba activate rapid
    /workspace/mambaforge/bin/pip3 install click ruff bio gdown
    /workspace/mambaforge/bin/gdown --folder --id 1Md0gD7VrmzlRM4xvxQKz2GG3Uyn00VHd
    mv rapid_curation_test_data test_data
    /workspace/mambaforge/bin/python3 -m pip install agp-tpf-utils/
    export PATH=/workspace:$PATH
    gp preview https://www.thebgacademy.org/BGA24/sessions/Genome-Curation
    clear
    export PATH=/workspace/mambaforge/bin:/workspace/rapid-curation:$PATH
    bash rapid-curation/welcome.sh

ports:
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
